### ISSUE TITLE
LunCo - lunar colony sim

### ISSUE THREAD

**Issue by Difint** [lamont-granquist/primervector-matlab#2]
Hi @lamont-granquist .

I've seen you've being working on mods for KSP.

I'm working on a similar but OPENSOURCE project: Lunar colony sim game

Is there any chance you'd like to collaborate?

[LunCo](https://github.com/lun-co/lunco-game)

LunCo will incorporate a lot of precise models like the one you've build here

**Comment by lamont-granquist** [comment]
nope, not at this time.
